main : main.cpp driver/driver.cpp zoo/zoo.cpp cell/cell.cpp point/point.cpp habitat/habitat.cpp cage/cage.cpp parse/parse.cpp animal/animal.cpp cage_list/cage_list.cpp
	g++ -o main main.cpp driver/driver.cpp zoo/zoo.cpp cell/cell.cpp point/point.cpp habitat/habitat.cpp cage/cage.cpp parse/parse.cpp animal/animal.cpp cage_list/cage_list.cpp -std=c++11
