main : Zoo/tour.cpp Zoo/Zoo.cpp Cell/Cell.cpp Point/Point.cpp Habitat/Habitat.cpp Cage/Cage.cpp parse/parse.cpp Animal/Animal.cpp CageList/CageList.cpp
	g++ -o test Zoo/tour.cpp Zoo/Zoo.cpp Cell/Cell.cpp Point/Point.cpp Habitat/Habitat.cpp Cage/Cage.cpp parse/parse.cpp Animal/Animal.cpp CageList/CageList.cpp -std=c++11

